### PR TITLE
build: create arm based images

### PR DESCRIPTION
**Pull request by maybeanerd**
In addition to releasing images for x86 architecture, we will now also publish images for arm.
This will allow more freedom in how to host squire.

### CODE REVIEW

**Comment by maybeanerd** [comment]
I didn't test this locally, let's see if the pipeline passes 👀

**Comment by maybeanerd** [comment]
Looks like phantom JS doesn't have arm binaries and is a dead project https://phantomjs.org/


Since it's apparently only useful for headless browsers testing, and I _think_ we're not actually doing that here, maybe there's a way to get rid of it

**Comment by maybeanerd** [comment]
This seems to have resolved the build issues.
Will do some local testing later to make sure the frontend still works before marking this PR ready

**Comment by maybeanerd** [comment]
tested locally, looking good

**Review by shaneherd — APPROVED** [review]

**Pull request merged**
